version: "3.7"

services:
  # c.f. https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build: .
    command: bash -c "packer --version && ls /root/.packer.d/plugins/packer-provisioner-serverspec && gem list | grep serverspec"
